#!/usr/bin/env python3
"""
Debug script to check localStorage data structure and validation issues
"""

print("=== LocalStorage Debug Guide ===")
print()
print("To debug the validation issue, please follow these steps in your browser:")
print()
print("1. Open the add_product_preview page")
print("2. Open browser developer tools (F12)")
print("3. Go to Console tab")
print("4. Run these commands to check localStorage data:")
print()
print("// Check what keys exist in localStorage")
print("console.log('LocalStorage keys:', Object.keys(localStorage));")
print()
print("// Check productForm data")
print("console.log('productForm:', localStorage.getItem('productForm'));")
print()
print("// Check productDescriptionForm data")
print("console.log('productDescriptionForm:', localStorage.getItem('productDescriptionForm'));")
print()
print("// Check productStocksForm data")
print("console.log('productStocksForm:', localStorage.getItem('productStocksForm'));")
print()
print("// Parse and check the actual data structure")
print("try {")
print("  const basicInfo = JSON.parse(localStorage.getItem('productForm') || '{}');")
print("  console.log('Parsed productForm:', basicInfo);")
print("  console.log('Product Name:', basicInfo.productName);")
print("  console.log('Category:', basicInfo.category);")
print("} catch(e) {")
print("  console.error('Error parsing productForm:', e);")
print("}")
print()
print("5. Copy the output and share it to identify the data structure issue")
print()
print("=== Common Issues ===")
print("- Data might be stored in sessionStorage instead of localStorage")
print("- Field names might be different (e.g., 'product_name' vs 'productName')")
print("- Data might be nested in a different structure")
print("- Form data might not be saved properly from previous steps")