"""Initial migration

Revision ID: f01c49872ffb
Revises: 
Create Date: 2025-10-24 22:36:18.153430

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f01c49872ffb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_oauth_provider', table_name='oauth')
    op.drop_index('idx_oauth_user_id', table_name='oauth')
    op.drop_constraint('oauth_ibfk_1', 'oauth', type_='foreignkey')
    op.create_foreign_key(None, 'oauth', 'user', ['user_id'], ['id'])
    op.alter_column('user', 'email',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
    op.drop_index('idx_user_email', table_name='user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_user_email', 'user', ['email'], unique=False)
    op.alter_column('user', 'email',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
    op.drop_constraint(None, 'oauth', type_='foreignkey')
    op.create_foreign_key('oauth_ibfk_1', 'oauth', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_index('idx_oauth_user_id', 'oauth', ['user_id'], unique=False)
    op.create_index('idx_oauth_provider', 'oauth', ['provider'], unique=False)
    # ### end Alembic commands ###
